### ISSUE TITLE
ADO Analysis failure

### ISSUE THREAD

**Issue by HerbWarren** [github/gh-migration-analyzer#13]
```
⠋ Fetching  zzz-OrangeBoard gh-migration-analyzer/src/api/azureDevOps.js:207
      repo._links.pullRequests.href +
                  ^

TypeError: Cannot read properties of undefined (reading 'pullRequests')
    at getAzureDevOpsRepoPR (gh-migration-analyzer/src/api/azureDevOps.js:207:19)
    at storeRepositoryPromise (gh-migration-analyzer/src/api/azureDevOps.js:168:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
``` 

For reference "zzz-OrangeBoard" is the last repo in the list (assuming alphabetical order is used), and it has no PRs; I'm not sure that repo is unique in that regard. In any event, there's not info on what repo the code is trying to use when it fails -- this is all I get for output.

**Comment by slenguyen** [comment]
Thanks for the bug report! This project is being lightly maintained at this point, and we have another project that can get you the same information (and more) here: https://github.com/github/gh-gei.  You can use this command on that tool to find the available options: `gh ado2gh inventory-report --help`.

**Comment by HerbWarren** [comment]
This turned out to be a case of a small number of old repos that I no longer had access to - not even read. I patched my local  clone to work around it, since we (probably) won't be migrating those anyway.
