### ISSUE TITLE
Docu inconsistency

### ISSUE THREAD

**Issue by ChristophHoyer** [github/gh-migration-analyzer#15]
Hej there!
In the readme you write in the first chapter:
> The tool currently supports migrations from Azure DevOps and GitHub Cloud as a source to GitHub Cloud as a destination.

And further down, in the PAT chapter, you also mention `GitHub Server (3.4+)`.

This does not fit together?

**Comment by slenguyen** [comment]
Excellent point! Thanks for the issue -- I've got a PR to remove the line about GHES.
